### ISSUE TITLE
numap-list doesn't run - lacks python3 support

### ISSUE THREAD

**Issue by lucasduffey** [usb-tools/nu-map#6]
`numap/apps/list_classes.py` isn't python3 compatible so it won't run properly.

If I try to install nu-map with python2 I get the `Facedancer is not compatible with python2; and requires python 3.0 or later" error

**Comment by ktemkin** [comment]
The Python3 support section of this has been resolved by ef4b73029; but there's still some work to be done to fix up `numap-scan`.

Ongoing discussion will be in #1.
